services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-sacabollos}
      MYSQL_USER: ${MYSQL_USER:-sacabollos}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-sacabollos_pass}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_pass}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./sacabollos_web_back
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./sacabollos_web_back:/code
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: sacabollos_web_back.settings
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE:-sacabollos}
      MYSQL_USER: ${MYSQL_USER:-sacabollos}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-sacabollos_pass}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./sacabollos_web_front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./sacabollos_web_front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - web

volumes:
  db_data: