# Generated by Django 4.2.11 on 2025-10-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(default='Spain', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('city', 'province', 'country')},
            },
        ),
    ]
