# Generated by Django 4.2.11 on 2025-10-06 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('company_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_time_hours', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('assigned', 'Assigned'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('tags', models.JSONField(default=list, help_text='Categories/tags as JSON array')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.companyprofile')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
