# Generated by Django 4.2.11 on 2025-10-06 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapista_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('date_completed', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapista_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='chapista_profile.chapistaprofile')),
            ],
            options={
                'ordering': ['-date_completed'],
            },
        ),
    ]
