# Generated by Django 4.2.11 on 2025-10-06 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapista_profile', '0001_initial'),
        ('company_profile', '0001_initial'),
        ('job_offer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('agreed_time_hours', models.IntegerField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapista_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapista_profile.chapistaprofile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.companyprofile')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job_offer.joboffer')),
            ],
        ),
    ]
