# Generated by Django 4.2.11 on 2025-10-06 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapista_profile', '0001_initial'),
        ('job_offer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('proposed_time_hours', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapista_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapista_profile.chapistaprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='job_offer.joboffer')),
            ],
            options={
                'unique_together': {('job', 'chapista_profile')},
            },
        ),
    ]
